apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: xenserver-default
  name: xenserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
